### ISSUE TITLE
How to remove the "trace" which appears each 10 lines in a root block?

### ISSUE THREAD

**Issue by carloscadux** [leodevbro/vscode-blockman#75]
Hi. I'd appreciate your help.
As shown in the screenshot below, for each 10 lines in a root block there is a light "trace" being rendered.
How to remove that trace?
Thank you!
 
![image](https://user-images.githubusercontent.com/7339389/158061967-3260fdb9-4d65-432d-8f5d-8cacab635465.png)

**Comment by leodevbro** [comment]
Hello, I guess this is a duplicate issue of this:
https://github.com/leodevbro/vscode-blockman/issues/52

Long story short:
I think it is a bug of VSCode, or Windows or both. I don't think that it is a bug of Blockman.

I made a `bug report` about it in the `vscode` repo:
https://github.com/microsoft/vscode/issues/137609

**Possible solution:**
If you have zoomed VSCode window, you can try resetting is:
Press F1, type "reset zoom" and click on `View: Reset Zoom`.

If you want to zoom, please don't use **View zoom (ctrl and "+")**, please use **font zooming feature (mouse wheel zoom)**.

**Comment by carloscadux** [comment]
Thanks for your prompt reply (and for this outstanding extension) 👍
Sorry for the duplicated thread.
I'm not using zoom but triggered "reset" (UI and font) just in case, but the issue is still there.
I upvoted the thread [https://github.com/microsoft/vscode/issues/137609](https://github.com/microsoft/vscode/issues/137609)

**Comment by leodevbro** [comment]
Thanks so much, well, please check the pixel resolution of your monitor, also the scaling percent of Windows (if you are using Windows 10).

Also maybe you should try installing VSCode Insiders (if you currently have VSCode) (or VSCode if you currently have VSCode insiders) and do not change any settings and just check how Blockman is working there. If you already have both, then this experiment cannot be done because we need totally clean software.

Also, please check exactly what is going on in the zoom settings. It must be `0` for best quality rendering.
![image](https://user-images.githubusercontent.com/54504880/158076737-2aefe61e-587f-4b8f-beeb-1de5d194bdf9.png)

**Comment by JC6123** [comment]
> Hello, I guess this is a duplicate issue of this: #52
> 
> Long story short: I think it is a bug of VSCode, or Windows or both. I don't think that it is a bug of Blockman.
> 
> I made a `bug report` about it in the `vscode` repo: [microsoft/vscode#137609](https://github.com/microsoft/vscode/issues/137609)
> 
> **Possible solution:** If you have zoomed VSCode window, you can try resetting it: Press F1, type "reset zoom" and click on `View: Reset Zoom`.
> 
> If you want to zoom, please don't use **View zoom (ctrl and "+"/"-")**, please use **font zooming feature (mouse wheel zoom)**.

That's interesting. Because in my issue, this bug disappears when I use **View zoom (ctrl and "+"/"-")** to zoom out, while **mouse wheel zoom** won't do. Besides, change the scale level into 100% in Windows 10 can also fix this problem.

**Comment by leodevbro** [comment]
Yeah, mouse wheel zoom does not fix the issue. When I said "mouse wheel zoom", I meant that it is a better alternative to "View zoom" because it does not cause such issues.

**Comment by leodevbro** [comment]
@carloscadux, @JC6123, Hello, I think this issue (strange horizontal lines) is fixed with the latest version of VSCode (1.66), so please update VSCode and check the issue again, and please tell me whether the situation is changed or not.

**Comment by JC6123** [comment]
> @carloscadux, @JC6123, Hello, I think this issue (strange horizontal lines) is fixed with the latest version of VSCode (1.66), so please update VSCode and check the issue again, and please tell me whether the situation is changed or not.

Yeah, seems it has been fixed now.

**Comment by carloscadux** [comment]
> @carloscadux, @JC6123, Hello, I think this issue (strange horizontal lines) is fixed with the latest version of VSCode (1.66), so please update VSCode and check the issue again, and please tell me whether the situation is changed or not.

v1.66 didn't fix the issue for me. Actually, the issue became more consistent.

Before v.166, the "trace" would disappear depending on the part of the code I was visualizing.
I'd say the issue was intermittent. 

After v.166 the "trace" became permanent, being shown each 10 lines starting from line 5, in all files I open in VSCode:
![image](https://user-images.githubusercontent.com/7339389/161401281-ea80c78d-eb5c-4e1d-a81b-ca0ee7432e68.png)

**Comment by leodevbro** [comment]
@carloscadux, have you tried, I don't know, restarting VSCode? Or maybe zoom to the value 0 (`Window: Zoom Level`)? Because, I guess your zooming is below 100%, and maybe you can try to set it to 100%, and then if you want smaller text, just use mouse wheel zooming, or font size. As I have experienced, Mouse wheel zooming and changing font size does not cause such strange horizontal lines. Only `Window: Zoom Level` causes it.

**Comment by leodevbro** [comment]
@carloscadux, also please try disabling GPU for VS Code.

![2022-04-06_08-40-23](https://user-images.githubusercontent.com/54504880/161897332-1c5ca1e4-100b-4ac9-9d02-fbff97cedf3d.png)


Here is the link:
https://code.visualstudio.com/docs/supporting/FAQ#_vs-code-is-blank

.
.
.
